name: thehobbyhopper
favicon: null
layout_spectrum: 0.63294
typography_spectrum: 0.49066
title: The Hobby Hopper
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75179110-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#743f1d'
    - '#864f28'
    - '#361906'
    - '#482810'
  brandStrength: 0.5
  lightness: 0.8680556588806212
  saturation: 0.9374954211525619
  rhythmicContrast: 0
purpose: []
